import fs from 'node:fs';
import path from 'node:path';

// The service and the manager each report this id, so the manager can tell when the installed
// service is an older build. `--if-missing` keeps an existing id (typecheck and test runs).
const file = path.resolve('src', 'shared', 'buildinfo.ts');
if (process.argv.includes('--if-missing') && fs.existsSync(file)) process.exit(0);
fs.writeFileSync(file, `// Generated by scripts/write-buildinfo.ts. Do not edit.\nexport const BUILD_ID = '${new Date().toISOString()}';\n`);
